SELECT * FROM customer
LIMIT 10;


-- Q1. What is the total revenue generated by male vs. female customers?

SELECT 
   gender, SUM(purchase_amount) total_revenue
FROM customer
GROUP BY gender
ORDER BY gender DESC;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT 
   customer_id ,
   SUM(purchase_amount) total_spent,
   (SELECT ROUND(AVG(purchase_amount),2) FROM customer) AS avg_purchase_amount
FROM customer 
WHERE discount_applied = 'Yes' AND 
      purchase_amount > (SELECT AVG(purchase_amount) FROM customer)
GROUP BY customer_id
ORDER BY customer_id;



-- Q3. Which are the top 5 products with the highest average review rating?

SELECT item_purchased,
       ROUND(AVG(review_rating)::NUMERIC,2) AS avg_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY 2 DESC
LIMIT 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT shipping_type,
       ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type IN ('Express','Standard')
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between
--  subscribers and non-subscribers.

SELECT 
   subscription_status,
   COUNT(customer_id) total_customers,
   ROUND(AVG(purchase_amount),2) avg_spent,
   ROUND(SUM(purchase_amount),2) total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY 4,3 DESC; 

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT 
   item_purchased,
   ROUND(SUM(100 * CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) discount_rate  
FROM customer
GROUP BY item_purchased
ORDER BY 2 DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total number of
--  previous purchases, and show the count of each segment.

WITH Customer_type AS
(
SELECT customer_id, previous_purchases,
   CASE
     WHEN previous_purchases <= 1 THEN 'New_Customers'
     WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning_Customers'
     ELSE 'Loyal_Customers'
   END customer_segment	  
FROM customer
)
SELECT customer_segment, COUNT(*) AS "Number of Customers"
FROM Customer_type
GROUP BY customer_segment;


-- Q8. What are the top 3 most purchased products within each category?

WITH CTE_Example AS
(
SELECT 
   item_purchased,
   category,
   COUNT(customer_id) AS total_orders,
   ROW_NUMBER() OVER(PARTITION BY CATEGORY ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category, item_purchased
)
SELECT 
   item_rank, category, item_purchased, total_orders
FROM CTE_Example
WHERE item_rank <= 3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to
--  subscribe?

SELECT subscription_status,
       COUNT(customer_id) repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status


-- Q10. What is the revenue contribution of each age group?

SELECT age_group,
       SUM(purchase_amount)
FROM customer
GROUP BY age_group
ORDER BY 2 DESC;


